### ISSUE TITLE
JellyCon suddenly unable to connect

### ISSUE THREAD

**Issue by krutburken** [mcarlton00/jellycon#21]
Not sure if this is a known issue (google got me nothing), but suddenly when I try to connect to Jellyfin 10.6.3, JellyCon throws me this error:

```
2020-08-23 09:28:21.284 T:2189402992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 3878: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.jellycon/service.py", line 54, in <module>
                                                check_server()
                                              File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/server_detect.py", line 439, in check_server
                                                du.authenticate()
                                              File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/downloadutils.py", line 576, in authenticate
                                                log.debug("AuthenticateByName: {0}".format(resp))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3878: ordinal not in range(128)
                                            -->End of Python script error report<--
```

OS: Raspberry Pi
Jellyfin Version: 10.6.3 (behind nginx reverse-proxy)
Kodi Version: 18.8 (LibreELEC 9.2.4)
Addon Version: 0.2.0

The other jellyfin-plugin works fine, aswell as the web ui. JellyCon has worked before... Not exactly sure what caused this

**Comment by mcarlton00** [comment]
Update: my current theory is that it's misinterpreting a blurhash as ascii codes and not behaving.  An example of these strings:
```
'ImageBlurHashes': {'Primary': {'9ce093c0a9e4e7691c4da2c704f299cf': 'elHm[?WDb^ofWE2|bbj]WrjZFzofnPj]ay^3e=buocbHb[WAozaejY',
                                'c8f9fab71a6768c226b4fcf7f9daace0': 'elHm[?WDb^ofWE2|bbj]WrjZFzofnPj]ay^3e=buocbHb[WAozaejY'}},
```

Next test is to strip those out of the payloads we receive from the server and see if the error still happens.  If that's the case, then it's probably luck of the draw when it happens.  Or not log the entire json response, since there's minimal situations where that would be helpful.  Logging still needs an overhaul anyway.
