### ISSUE TITLE
Issues with playback of files with special characters in filename

### ISSUE THREAD

**Issue by Gangelie** [mcarlton00/jellycon#47]
Jellycon is not able to play files with special characters in filename. For example files containing the following characters: ěščřýáíú§ů and many more. 

If I chose to transcode the movie the movie will be played. 

I can also not remote control the Jellycon via the web interface and force to play the movie. 

This is an issue as a huge part of my media library is in czech language and until now I did not need to rename the files after downloading so this would mean a huge time invest in manually find and rename the files.

**Comment by mcarlton00** [comment]
Just to be clear, is it when special characters are in the filenames, or the video title?

Would you be able to check the logs for any errors?  I'm assuming this is a fairly common Unicode issue, in which case we should have a traceback in the logs for where it failed at. https://kodi.wiki/view/Log_file/Easy

**Comment by Gangelie** [comment]
Hi,

here are the Error messages from Kodi

`2021-01-25 19:07:02.871 T:1761112960  NOTICE: JELLYFIN.resources.lib.functions -> INFO::resources/lib/functions.py:979 Sending jellycon_play_action : {u'auto_resume': '-1', u'audio_stream_index': None, u'item_id': u'e52b81afe34c67973d122ae0a7c51dae', u'force_transcode': False, u'subtitle_stream_index': None, u'action': u'play', u'media_source_id': u''}
2021-01-25 19:07:03.054 T:1658176384  NOTICE: JELLYFIN.resources.lib.play_utils -> INFO::resources/lib/play_utils.py:1231 Received jellycon_play_action : {u'auto_resume': u'-1', u'audio_stream_index': None, u'action': u'play', u'force_transcode': False, u'subtitle_stream_index': None, u'item_id': u'e52b81afe34c67973d122ae0a7c51dae', u'media_source_id': u''}
2021-01-25 19:07:03.065 T:1937267136   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.jellycon/?item_id=e52b81afe34c67973d122ae0a7c51dae&mode=PLAY]
2021-01-25 19:07:03.791 T:1658176384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe1' in position 85: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/play_utils.py", line 1232, in onNotification
                                                play_file(play_info, self.monitor)
                                              File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/tracking.py", line 23, in wrapper
                                                value = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.jellycon/resources/lib/play_utils.py", line 394, in play_file
                                                log.info("Play URL: {0} Playback Type: {1} ListItem Properties: {2}".format(playurl, playback_type, listitem_props))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 85: ordinal not in range(128)
                                            -->End of Python script error report<--`


and these is what Jellyfin server is showing

`[2021-01-25 19:07:03.632 +01:00] [INF] [86] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: DeviceProfile { Name: "Kodi", Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 75000000, MaxStaticBitrate: 75000000, MusicStreamingTranscodingBitrate: 256000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 5, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: "-hevc,h265", Type: Video }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: null, AudioCodec: null, VideoCodec: null, Type: Photo }], TranscodingProfiles: [TranscodingProfile { Container: null, Type: Audio, VideoCodec: null, AudioCodec: null, Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "ac3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "8", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "jpeg", Type: Photo, VideoCodec: null, AudioCodec: null, Protocol: null, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [SubtitleProfile { Format: "srt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "srt", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "smi", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "dvdsub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgs", Method: External, DidlMode: null, Language: null, Container: null }] }
[2021-01-25 19:07:03.643 +01:00] [INF] [86] MediaBrowser.Api.Playback.MediaInfoService: User policy for "pi". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-01-25 19:07:03.643 +01:00] [INF] [86] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Kodi", Path: "\\XXXXXXXX:XXXXXXXXX@192.168.1.102\festplatte1\Cinema\Puss in boots (2009)\Kocour v botÃ¡ch.avi", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 19:07:03.643 +01:00] [INF] [86] MediaBrowser.Api.Playback.MediaInfoService: RemoteClientBitrateLimit: 2000000, RemoteIp: "192.168.1.11", IsInLocalNetwork: True
[2021-01-25 19:07:03.643 +01:00] [INF] [86] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Kodi", Path: "\\XXXXXXXXX:XXXXXXXX@192.168.1.102\festplatte1\Cinema\Puss in boots (2009)\Kocour v botÃ¡ch.avi", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-01-25 19:07:03.643 +01:00] [INF] [86] MediaBrowser.Api.Playback.MediaInfoService: RemoteClientBitrateLimit: 2000000, RemoteIp: "192.168.1.11", IsInLocalNetwork: True
[2021-01-25 19:07:03.643 +01:00] [INF] [86] MediaBrowser.Api.Playback.MediaInfoService: Profile: "Kodi", Path: "\\XXXXXXXX:XXXXXXXXX@192.168.1.102\festplatte1\Cinema\Puss in boots (2009)\Kocour v botÃ¡ch.avi", isEligibleForDirectPlay: True, isEligibleForDirectStream: True`

I did only XXXXX out the username and password for my share


In this case the filename is: \festplatte1\Cinema\Puss in boots (2009)\Kocour v botách.avi

If I would rename it in Kocour v botach.avi the issue would be gone.

**Comment by mcarlton00** [comment]
The good news is that it should be a straightforward fix. It looks to be failing on a log line, ironically enough.  What device are you running this on?  There may be an easy way for us to make sure it's just the log line that's causing issues.

**Comment by Gangelie** [comment]
I am running Kodi on an Raspberry Pi 3 Model B. Would be great if its only a small fix. If you tell me which file which line should be changed I sure could test it out.

**Comment by mcarlton00** [comment]
All you should need to do is comment out line 394 of `/storage/.kodi/addons/plugin.video.jellycon/resources/lib/play_utils.py`.  It should look like `#log.info("Play URL: {0} Playback Type: {1} ListItem Properties: {2}".format(playurl, playback_type, listitem_props))` when you're done.  Once that's done restart Kodi and test again.

**Comment by Gangelie** [comment]
Yes this is working.

Thx.

**Comment by mcarlton00** [comment]
Perfect.  I'll make sure that's changed before the next release.

**Comment by mcarlton00** [comment]
Can you do a test with the current master branch?

https://github.com/mcarlton00/jellycon/archive/master.zip

I'm unable to replicate this locally, so I suspect it has something to do with system language/encoding settings.  In theory this should make it behave more like python 3 which shouldn't have these problems.

**Comment by Gangelie** [comment]
is it necessary upgrade Kodi to version 19 or 18.9 is sufficient for testing?

**Comment by mcarlton00** [comment]
18 is still supported for the foreseeable future.  I've just released version 0.4.0 into the addon repo, so you can test that instead of downloading that zip file to verify if it's working.  Otherwise I'll find a fix for 0.4.1

**Comment by Gangelie** [comment]
ok I tried to install id however Kodi kept telling me that "The file has not the correct structure" This happens with the zip from your post above and as well with the version in the repo :(
Something I am missing?

**Comment by mcarlton00** [comment]
Are you using the repo located at https://kodi.jellyfin.org?

Because of the way Kodi 18 and Kodi 19 differ, downloading the master zip file and installing it directly doesn't work anymore.  We've had to set up a build pipeline that creates different addons for the different Kodi versions.  The versions in that repo should be fully functional. I've just installed them myself to be sure and didn't have any issues with it.

**Comment by Gangelie** [comment]
OK I did test it today and unfortunately it did not play the file. In the attached log file i tried to start the movie at timestamp 2021-03-06 21:03:00

[kodi.log](https://github.com/jellyfin/jellycon/files/6096036/kodi.log)

**Comment by mcarlton00** [comment]
Well it's not throwing the error that it was, but it's also not really throwing any traceable errors anymore.  Are you using network path substitution in the server?  I see a lot of references to a SMB location that I wouldn't expect to see on client side, and I didn't think that setting was used in anything other than Jellyfin for Kodi.

**Comment by Gangelie** [comment]
I had this setup actually on server side. I did delete the network path substitution on the server and nothing changed. Here the new log file. I did try to play 2 files, the first with special character which did not play and the second without but surprisingly this did not play as well (with a message something like "Some file could not be played or something like that). I switch back to addon version 0.3.1 and everything works again fine so server side is ok.
[kodi3.log](https://github.com/jellyfin/jellycon/files/6096127/kodi3.log)

**Comment by mcarlton00** [comment]
I still can't replicate this.  I've renamed files to have the special characters you mentioned, I've modified metadata and added `ěščřýáíú§ů` to titles of movies, I've changed my Kodi language to Czech.  I even made a whole new jellyfin server to make sure there wasn't historical data in my database that was causing it to not match.  It's played every time without fail.  I'm stuck, and I can't think of how or why it would be failing to play at this point.  The original issue was a comparison between strings and bytes, and since I'm seeing the `Play URL` line in your logs that has been fixed, but something else is failing further down the line and I can't understand what it is.

```
2021-03-06 22:20:18.752 T:1333785472  NOTICE: JELLYFIN.resources.lib.functions -> INFO::resources/lib/functions.py:969 Sending jellycon_play_action : {u'auto_resume': '-1', u'audio_stream_index': None, u'item_id': u'0c5c3d4c6c7599e9aa676fc5768e4725', u'force_transcode': False, u'subtitle_stream_index': None, u'action': u'play', u'media_source_id': u''}
2021-03-06 22:20:20.210 T:1333785472  NOTICE: JELLYFIN.resources.lib.play_utils -> INFO::resources/lib/play_utils.py:376 Play URL: {jellyfin-server}/Videos/0c5c3d4c6c7599e9aa676fc5768e4725/stream?static=true&PlaySessionId=b9a0e68170e84474b673295727b0eca4&MediaSourceId=0c5c3d4c6c7599e9aa676fc5768e4725 Playback Type: 1 ListItem Properties: []
2021-03-06 22:20:21.027 T:1937317296  NOTICE: VideoPlayer::OpenFile: http://192.168.1.102:8096/Videos/0c5c3d4c6c7599e9aa676fc5768e4725/stream?static=true&PlaySessionId=b9a0e68170e84474b673295727b0eca4&MediaSourceId=0c5c3d4c6c7599e9aa676fc5768e4725
2021-03-06 22:20:21.038 T:1266967424  NOTICE: Creating InputStream
2021-03-06 22:20:21.051 T:1266967424  NOTICE: Creating Demuxer
2021-03-06 22:20:21.377 T:1937317296   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.jellycon/?item_id=0c5c3d4c6c7599e9aa676fc5768e4725&mode=PLAY]
2021-03-06 22:20:21.413 T:1937317296  NOTICE: CVideoPlayer::CloseFile()
```
This seems to be indicating that the actual error is coming from Kodi itself, but that doesn't make any sense.  At this moment, I'm out of ideas.

**Comment by Gangelie** [comment]
OK I will setup these days a new Kodi Raspberry just to be sure that it's nothing in the current installation. I will let you know.

**Comment by Gangelie** [comment]
Hi,
I had the time to test with fresh installed Jellyfin and Kodi. I did install Jellyfin fresh using docker on the server and installed a new Kodi image fresh downloaded from libreelec website. Nothing changed. Content is still not played. Attached the log of the playback.  I tried to open the playback url manually in VLC and its working but in kodi not.
I tried then to play other content and its not working either :(
I then installed the newest version of Kodi on my laptop and the same result.

[kodi-log.log](https://github.com/jellyfin/jellycon/files/6162414/kodi-log.log)
